### ISSUE TITLE
「タンクトップ」と「タンク」の英名が同じ問題

### ISSUE THREAD

**Issue by ysds** [ysds/acnh-gachi-complete#102]
どちらも英名が **tank** が原因なのか、 https://github.com/NooksBazaar/google-sheets-to-json から出力される json ファイルで同じ `"name": "tank"` にバリエーションが統合されてしまっている。

結果、以下のような問題が発生

![image](https://user-images.githubusercontent.com/4065765/140457806-3c6e49d6-32c9-4c9a-a6f9-95c395c85608.png)

**Comment by FURI-J** [comment]
@ysds 

SpreadsheetのNameは英名をそのまま持ってきている感じですね。
MSBT上も「タンクトップ」と「タンク」の英名は同じ"tank" になっています。

Editors' Copyじゃない正式なシートに反映済みのようなので
このタイミングでリネームを提案して対応してもらえるのか不透明ですね。
「google-sheets-to-json」で出力するときに「タンク」のnameを無理やり置き換えるしかないかも、、？

**Comment by ysds** [comment]
@FURI-J まだ取り組む時間がなくて試していないのでわかりませんが、以下の定義で別 json に出力を分けるといけそうな気がしています。
https://github.com/NooksBazaar/google-sheets-to-json/blob/master/src/index.ts

**Comment by ysds** [comment]
https://github.com/NooksBazaar/google-sheets-to-json/blob/0f6cafb4407c8c769aa7941b4f1750b03a1a758a/src/index.ts#L477

```diff
- let key = (rawItem.name as string).toLowerCase();
+ let key = (rawItem.name as string).toLowerCase() + rawItem.sourceSheet;
```

上記のような修正でいけそうです。

**Comment by FURI-J** [comment]
@ysds 

名前が同じままだとチェック状態（collected）が共有されて挙動が少しおかしくなりますね。
→タンクの名前を変えるかuniqueEntryIdを定義する？？

**Comment by ysds** [comment]
@FURI-J そうでした！わかってたのですが、すっかり忘却してました。

**Comment by ysds** [comment]
やっつけですが https://github.com/ysds/acnh-gachi-complete/commit/fdb08770447b24430137127ad43f25c95b1f532c で修正しました、
