### ISSUE TITLE
アイテム名変更に伴う対処

### ISSUE THREAD

**Issue by ysds** [ysds/acnh-gachi-complete#106]
下記の現象について、ロード時にコレクションデータの該当キーを旧→新にリネームする処理を追加する方向で進めようと思います。

https://twitter.com/dreamtowerx/status/1456819930418929668?s=21

https://twitter.com/dreamtowerx/status/1456825318841278469?s=21

Cc/ @FURI-J

**Comment by FURI-J** [comment]
旧キーのデータはそのまま残っているようなのでリネームでいけそうですね！
