### ISSUE TITLE
カタログフィルタの挙動修正

### ISSUE THREAD

**Issue by FURI-J** [ysds/acnh-gachi-complete#112]
V2でカタログの挙動が少し変更されたようです。
ガチコンプ（カタログフィルタ）と実機で挙動が異なるアイテムをまとめました。

| アイテム種別 | ガチコンプ | 実機 |
| ------------- | ------------- |------------- |
| シーズンアイテム  | カタログ掲載なし  |  カタログ掲載あり<br>ただし、期間外アイテムは「きかんがい」表示 |
| マリオコラボアイテム  | カタログ掲載なし  |  カタログ掲載あり |
| サンリオコラボアイテム  | カタログ掲載なし  |  カタログ掲載あり |
| ポケ森コラボアイテム  | カタログ掲載なし  |  カタログ掲載あり |
| Nintendo Switch Online加入者特典アイテム<br>（「Nintendo Switch Lite」と「たぬきかいはつのスクエアラグ」）  | カタログ掲載なし  |  カタログ掲載あり<br>ただし、Nintendo Switch Liteが買えない日は「オーダーふか」表示 |

これらのアイテムは元のSpreadSheetで「Not in catalog」となっているため、
ガチコンプで「カタログ掲載なし」扱いとなっています。

SpreadSheetは実機データ（ItemParam.bcsv）からツールでデータ生成しているようで、これらのアイテムの実機データは以下の通り「NotSee」となっています。
![image](https://user-images.githubusercontent.com/75649436/141612819-46f610ae-c8cf-4127-be3f-d4dcaec1203b.png)

アイテム定義データ上は「NotSee」にもかかわらずカタログには出ているので、表示させるための特別な処理が組まれていると思われます。

SpreadSheetが修正される可能性もあり、しばらく様子見で良いかと思いますが、ひとまずIssueとして登録します。

**Comment by ysds** [comment]
@FURI-J 「カタログ掲載なし」がほとんど意味をなさないような気がしましたので、typeFilters を以下のように見直してみました。
https://github.com/ysds/acnh-gachi-complete/blob/bdcbca115f3c2184b00703bf24c478378fb7b243/src/utils/filter.js#L10-L41
非売品、非売品（DIY）、非売品（DIYを除く）は本当に合っているかは未確認です。

一旦本 Issue はクローズしますが、もしまだ問題などありましたらお知らせいただけると幸いです！
