### ISSUE TITLE
【機能追加】カテゴリ追加：ははシリーズ

### ISSUE THREAD

**Issue by FURI-J** [ysds/acnh-gachi-complete#12]
需要がありそうなので追加のご検討をお願いします。
→ よろしければプルリク投げられます。

参考：
https://twitter.com/nene_no_moriaka/status/1339084181238734850?s=20

![image](https://user-images.githubusercontent.com/75649436/103192699-f0a21c80-491c-11eb-9351-06c96cd9091e.png)

**Comment by ysds** [comment]
プルリクは自由に投げて頂いて大丈夫ですよ👍

**Comment by ysds** [comment]
#14 にて対応
