### ISSUE TITLE
パピパラのシェアハウス管理

### ISSUE THREAD

**Issue by ysds** [ysds/acnh-gachi-complete#123]
質問箱より

シェアハウスを組んだペアを管理したい

**Comment by FURI-J** [comment]
個人的にも欲しい機能なので、仮実装して検討してみました。

色々課題があり、仕様はご相談させていただきたいです。

**仕様案**
* 新しいカテゴリ「別荘（ハウスシェア）」を追加する
* ハウスシェアする相手は「パートナー」と表記する（実機で「パートナーを探そう」という文言あり）
* 別荘（既存の単身）カテゴリのモーダルからパートナーを設定できるようにする
* 別荘（ハウスシェア）カテゴリのモーダルからハウスシェアを解消できるようにする
* ハウスシェアした住民は別荘（単身）カテゴリから非表示にする
※別荘（単身）＋別荘（ハウスシェア）＋別荘（VIP）の合計数をツクッターの別荘数と合わせたいため
* 別荘（ハウスシェア）のアイテムは状態（未取得・取得済・配布可）を持たない
※状態を持たせることも可能だが、collectedのキーを住民2人の組み合わせとした場合、組み合わせが8万通り以上あり、collectedが肥大化する可能性＆状態管理の需要もなさそうなため。
  * 未取得時の表示で固定 
  * タップしても状態を変えない
  * リストビューでチェックボックスを非表示にする
  * 関連する一括操作を非表示にする
* アイテムモーダル
  * 「欲しいものリストに追加」「配布可能な在庫数」は非表示にする
* コンプ率
  * 別荘（ハウスシェア）ではコンプ率を100%固定（分母＝分子＝ハウスシェアの数）とする
  * 全体コンプ率にも100%固定で表示する
  * ハウスシェアの結果、別荘（単身）カテゴリのアイテム数が増減することになるが、別荘（単身）カテゴリのコンプ率表示に反映する
* 検索
  *  別荘（ハウスシェア）のアイテムは検索対象外とする
  ※検索対象に含めることは可能だが、実装のコストに比べると需要が低そうなため。
  * ハウスシェアした住民は別荘（単身）カテゴリから非表示にはなるが、検索にはヒットする
  ※ヒットさせないようにするには実装上の考慮が必要＆ヒットしても特に不都合はなさそうなため。
* シェア
  *  別荘（ハウスシェア）カテゴリはシェア可能とする

以下は仮実装した検討結果です。

・別荘のモーダルに「ハウスシェアパートナーを追加」ボタン設置
![image](https://user-images.githubusercontent.com/75649436/145699554-9fbf87f9-2cd0-4e0f-aa94-327de832c7d5.png)

・上記追加ボタンでパートナー選択
![image](https://user-images.githubusercontent.com/75649436/145699595-22588c31-780a-45f0-b1db-77c09f8e06f4.png)

・選択後
![image](https://user-images.githubusercontent.com/75649436/145699616-6a582062-3982-4638-adb7-cc988deb9d65.png)

・別荘（ハウスシェア）カテゴリを追加＆表示サンプル
![image](https://user-images.githubusercontent.com/75649436/145699628-889478a4-159a-4d0f-b4d2-5a76d6fcce67.png)

**Comment by ysds** [comment]
検討いただきありがとうございます！

ハウスシェアが解放されるまで進めていないのでわからない部分があるので教えてください！

* ハウスシェアの概念的に「メイン（主となるキャラ）」と「パートナー」的なものがある
* ツクッターに表示されるテーマは「メイン」のものが表示される
* ハウスシェアの解消は「パートナー」しかできない

これらの認識はあっていますでしょうか？

**Comment by FURI-J** [comment]
@ysds 

> ハウスシェアの概念的に「メイン（主となるキャラ）」と「パートナー」的なものがある
> ツクッターに表示されるテーマは「メイン」のものが表示される

上記について、ハウスシェアの流れとしては
① メインキャラの別荘を作る→完成
② 完成後にメインキャラを改めて訪問
③ ハウスシェアを勧める
④ パートナーの選択
⑤ ①の別荘をハウスシェア用にリフォーム→完成
⑥ ツクッターには「【メインキャラ名】&【パートナー名】」で表示
になります。


> ハウスシェアの解消は「パートナー」しかできない

ハウスシェア完成後に訪問すると「メインキャラ」と「パートナー」の二人がいて、
どちらに話しかけてもハウスシェアは解消可能です。
→話しかけたほうのキャラが独立（単身別荘のテーマを作り直し）＆ハウスシェアの別荘はそのままで、話しかけていない住民が1人で残る

**Comment by ysds** [comment]
ありがとうございます。
ツクッターの各カード？に表示されるテーマはメインキャラのものになりますでしょうか？

**Comment by FURI-J** [comment]
テーマはハウスシェア完成時に
・新しく設定する
・メインキャラのテーマのまま変更しない
のどちらかを選択できます。

**Comment by ysds** [comment]
連投ですみません、VIPとのハウスシェアはできないで合ってますでしょうか？

**Comment by FURI-J** [comment]
はい！
VIPとのハウスシェアできないです。
また、エイブルシスターズなどのハウスシェアのVIPもシェア解消はできないようです。

VIPの別荘を訪問→ハウスシェアを勧める→やんわり拒否される
通常住民の別荘を訪問→ハウスシェアを勧める→amiiboでVIP呼び出し→「この方にはお声がけできません。」と表示されて呼び出せない

**Comment by ysds** [comment]
ご確認ありがとうございます！

UI的な点として大きな検討項目は、カテゴリーを増やすかどうかかなと思います。
なんとなく今の別荘カテゴリだけでやれないかと思っています。

**Comment by FURI-J** [comment]
> ※状態を持たせることも可能だが、collectedのキーを住民2人の組み合わせとした場合、組み合わせが8万通り以上あり、
> collectedが肥大化する可能性＆状態管理の需要もなさそうなため。

上記の懸念があったので、状態を管理しないハウスシェアを別カテゴリにした案としました。

理論上は8万通り以上ですが、実際には多くても数百だと思うので、
ハウスシェアも状態管理ありにして今の別荘カテゴリに追加する形でも良いかもしれません。

**Comment by ysds** [comment]
@FURI-J 
実装ありがとうございます。
両方触ってみてですが、やはり同じ別荘カテゴリーでやってしまうのがよいと思います。

collectedは二人の組み合わせを新たに作って取得管理する必要ってありますでしょうか？
ハウスシェア時もメインキャラのキーだけで対応できないかなと思っています。

**Comment by FURI-J** [comment]
@ysds 

たしかに、メインキャラで管理しても不都合はなさそうです。
（そもそも状態が重視されるカテゴリではないので影響は小さそう）
以下で対応いたしました。
https://github.com/ysds/acnh-gachi-complete/issues/123#issuecomment-992005091

**Comment by ysds** [comment]
@FURI-J さん

別荘（ハウスシェア）の方の PR になっておりますが、やはり分けた方がよいでしょうか？
できればカテゴリを増やさずに同じ別荘内でやってしまえないかと思っています。

**Comment by FURI-J** [comment]
@ysds 

すみません完全に取り違えていました。
#134 リオープンしました。

**Comment by ysds** [comment]
Closed by #134
