### ISSUE TITLE
【機能追加】カテゴリ追加：マイル家具

### ISSUE THREAD

**Issue by FURI-J** [ysds/acnh-gachi-complete#13]
ははシリーズ同様、マイル家具のみでの交換は頻繁に行われている様子なのである程度の需要がありそう。
→ こちらもよろしければプルリク投げられます。

![image](https://user-images.githubusercontent.com/75649436/103192757-2cd57d00-491d-11eb-9e33-6d3d7d500226.png)

**Comment by ysds** [comment]
#15 で対応
