### ISSUE TITLE
やぶれたはくいとよごれたタンクトップ

### ISSUE THREAD

**Issue by ysds** [ysds/acnh-gachi-complete#132]
質問箱より

やぶれたはくいとよごれたタンクトップのカラバリが入手不可のため削除して欲しい

**Comment by ysds** [comment]
現時点で入手例は確認できず。
海外でも？

**Comment by FURI-J** [comment]
任天堂サポートからの回答は「教えられません」だそうです。
https://twitter.com/moco_2020/status/1458654004007751680?s=20

Nookazonでたまに見かけますが、改造品なのか正規品なのか区別がつきません・・。
https://nookazon.com/product/1331199940

**Comment by ysds** [comment]
c0af60661840ef23eb82cc3e797377b2c7032936 にてメモを追加

**Comment by ysds** [comment]
2.0.4 でバグが解決したようなので c0af606 をリバート
