### ISSUE TITLE
しゅるい順ソート対応

### ISSUE THREAD

**Issue by FURI-J** [ysds/acnh-gachi-complete#140]
フォロワーさんのツイートより
https://twitter.com/kyasmaaaru/status/1471140918078349314?s=20

＜発生している問題＞
ガチコンプはあいうえお順だが、
「こもの」カテゴリであいうえお順にすると、家具と写真が混在して見辛い。
![image](https://user-images.githubusercontent.com/75649436/146550413-3ac4455f-67c2-42c8-822e-41de0acd4f8f.png)

＜原因＞
V2から写真・ポスターの「しゅるい順」ソート仕様が変わったため。
* V1：種類内であいうえお順（写真なら「写真あ～ん」）
* V2：種類内で種族別→あいうえお順（写真なら「ネコの写真あ～ん」「イヌの写真あ～ん」…）

＜対策案＞
写真・ポスターカテゴリにソートボタンを追加する。
→「名前順」「種類順」
→ 実機に合わせて「種類順」をデフォルトにする。

@ysds 
特に問題なければ上記内容で週末対応します。

**Comment by ysds** [comment]
@FURI-J 
ご検討ありがとうございます。

まずは1点確認させてください。
- 現在ガチコンプではname, id の二種類の order キーを持っていますが、種類に相当する新しいキーを追加するということでしょうか？
- それとも、実機順を種類順にラベル変更するということでしょうか？

> → 実機に合わせて「種類順」をデフォルトにする。

ガチコンプはカテゴリー毎にソート順設定を保存しているわけではないため、他のカテゴリーにも影響があるので、ポスターや写真に興味がないユーザーへの影響が危惧されます。

シェア画面はすでにid順（種類順？）がデフォルトですが、シェア画面でポスターや写真を種類順で見たいのか（見やすいのか）疑問です。
この方は収納の種類順は探しにくいとおっしゃっているので…。

ですので、ガチコンプはデフォルトで名前順がいいと考えますがいかがでしょうか？

**Comment by FURI-J** [comment]
@ysds 

> ガチコンプはカテゴリー毎にソート順設定を保存しているわけではないため
すみません、↑を考慮できていませんでした＆ご指摘通り
種類順はかなり見辛い（探し辛い）ので名前順デフォルトが妥当そうです。
おそらく、収納と見比べるときしか種類順は活用されないかと思います。

シェア画面でも名前順がデフォルトになるよう、
「種類に相当する新しいキーを追加」でどうでしょうか？

**Comment by ysds** [comment]
新しくキーを追加するのでも、後者の案でもどちらでもいいですよ！

**Comment by FURI-J** [comment]
写真とポスターは #142 で対応しました。

他の家具カテゴリも種類順は追加可能です。需要がありそうなら対応いたします。

**Comment by ysds** [comment]
Closed by #142
