### ISSUE TITLE
一括シェアで公開カテゴリ未選択の時すべて公開されてしまう

### ISSUE THREAD

**Issue by ysds** [ysds/acnh-gachi-complete#38]
一括シェアで、どのカテゴリも公開しなければ（初期状態）、「データは非公開です」の旨を表示するようにしていたが、いつのまにかすべて表示されるようになってしまっている。

![DFD52EF0-FBEC-4524-8B4E-E96FEEDE5336](https://user-images.githubusercontent.com/4065765/104524894-6a871500-5642-11eb-91de-ca801602a3a7.jpeg)

**Comment by FURI-J** [comment]
原因はたぶん [ここ](https://github.com/ysds/acnh-gachi-complete/commit/a8c884d75012a1013c6865586881585823269751#diff-6c3706d1fee4c2747d4950672037b33cba8cd859fd27078469b1877057cf76b6R562 ) だと思います。
falseを返せば「データは非公開です」になりましたが、
副作用があるかもしれません。

**Comment by ysds** [comment]
現状を許容します。
9b6c788120d701f510945f69cf29e1edf0e17ebf にて表示調整
