### ISSUE TITLE
クラウド同期間隔の見直し

### ISSUE THREAD

**Issue by FURI-J** [ysds/acnh-gachi-complete#44]
同期障害の件、ご迷惑をおかけいたしました。
同期が増えるのは認識していましたが、アクティブユーザ数が不明だったため
影響度が読めず、結果的に事前確認しないままPRを出してしまいました。
念のため確認すべきでした。

Revertされた問題に対するIssueを残させていただきます。

---

#41 だと同期が多すぎてFirestoreの無料枠を超えてしまうため、別の方法を考える。

## 現状
差分を検出できるのが1回だけなので、自動同期はアクセス後に最大1回

**現状起こりうる問題**
- スマホでチェックして、そのあとにPCで見るとチェックが反映されていない
- チェック後に同期されず、シェア画面で見るとチェックが反映されていない

※いずれも画面の再読み込みで同期→解消されるので、
回避は可能（ユーザは経験的にこの回避方法を知っている？）

## 対策案1
#41 の修正＋同期間隔を3秒から大きくする。
どれぐらい大きくするのが妥当なのか判断が難しい。
## 対策案2
- 定期同期処理は廃止
- アクセス直後に1度だけ同期
- さらにシェアボタン押下で同期

**Comment by ysds** [comment]
案2の方向で考えています。
