### ISSUE TITLE
【要検討】リアクションの並び順

### ISSUE THREAD

**Issue by FURI-J** [ysds/acnh-gachi-complete#5]
あいうえお順ではなく実機の表示順に合わせるべき？

**Comment by ysds** [comment]
情報ソースに並び順の情報がなさそうです。
独自に情報を持つしかないのであれば、あつ森のアップデートに追従する負荷が高くなるので対応しない予定です。
情報ソースに並び順が追加されれば対応を検討いたします。

**Comment by FURI-J** [comment]
ご検討ありがとうございます。
SpreadsheetのDiscord覗いたら、ちょうど今日developerメンバ（？）で追加されたようです。
問題なければ近いうちにマージされて公開されると思われます。

> - Added # column (in-game menu sort order) to Reactions tab

![image](https://user-images.githubusercontent.com/75649436/102678507-593a1c80-41ec-11eb-8503-5bd8be9c241a.png)

**Comment by ysds** [comment]
bab1dc252a4d6c154c5ea0b6f269cac4607732b3 にて対応
