### ISSUE TITLE
【機能追加】全カテゴリのコンプ率表示（ガチコンプ率）

### ISSUE THREAD

**Issue by FURI-J** [ysds/acnh-gachi-complete#9]
カテゴリを跨いだコンプ率（ガチコンプ率）の表示機能があると良いかと思いました。
※「いし」とかのアイテムデータを削除したりしないと算出が難しそう。

**Comment by ysds** [comment]
a8c884d75012a1013c6865586881585823269751 にて対応。
「その他」は全体率の計算対象外としました。
